// DO NOT EDIT THIS FILE! It is auto-generated.
const propTypes = {
  "Accordion": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "defaultExpanded": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableGutters": {
      "isRequired": false,
      "type": "bool"
    },
    "expanded": {
      "isRequired": false,
      "type": "bool"
    },
    "square": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "AccordionActions": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableSpacing": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "AccordionDetails": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "AccordionSummary": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "expandIcon": {
      "isRequired": false,
      "type": "node"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    }
  },
  "Alert": {
    "action": {
      "isRequired": false,
      "type": "node"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "closeText": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "role": {
      "isRequired": false,
      "type": "string"
    },
    "severity": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "AlertTitle": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "AppBar": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "inherit",
        "primary",
        "secondary",
        "transparent"
      ]
    },
    "enableColorOnDark": {
      "isRequired": false,
      "type": "bool"
    },
    "position": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "absolute",
        "fixed",
        "relative",
        "static",
        "sticky"
      ]
    }
  },
  "Autocomplete": {
    "autoComplete": {
      "isRequired": false,
      "type": "bool"
    },
    "autoHighlight": {
      "isRequired": false,
      "type": "bool"
    },
    "autoSelect": {
      "isRequired": false,
      "type": "bool"
    },
    "blurOnSelect": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "mouse",
        "touch"
      ]
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "clearIcon": {
      "isRequired": false,
      "type": "node"
    },
    "clearOnBlur": {
      "isRequired": false,
      "type": "bool"
    },
    "clearOnEscape": {
      "isRequired": false,
      "type": "bool"
    },
    "clearText": {
      "isRequired": false,
      "type": "string"
    },
    "closeText": {
      "isRequired": false,
      "type": "string"
    },
    "disableClearable": {
      "isRequired": false,
      "type": "bool"
    },
    "disableCloseOnSelect": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disabledItemsFocusable": {
      "isRequired": false,
      "type": "bool"
    },
    "disableListWrap": {
      "isRequired": false,
      "type": "bool"
    },
    "disablePortal": {
      "isRequired": false,
      "type": "bool"
    },
    "filterSelectedOptions": {
      "isRequired": false,
      "type": "bool"
    },
    "forcePopupIcon": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "freeSolo": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "handleHomeEndKeys": {
      "isRequired": false,
      "type": "bool"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "includeInputInList": {
      "isRequired": false,
      "type": "bool"
    },
    "inputValue": {
      "isRequired": false,
      "type": "string"
    },
    "loading": {
      "isRequired": false,
      "type": "bool"
    },
    "loadingText": {
      "isRequired": false,
      "type": "node"
    },
    "multiple": {
      "isRequired": false,
      "type": "bool"
    },
    "noOptionsText": {
      "isRequired": false,
      "type": "node"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "openOnFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "openText": {
      "isRequired": false,
      "type": "string"
    },
    "options": {
      "isRequired": true,
      "type": "array"
    },
    "popupIcon": {
      "isRequired": false,
      "type": "node"
    },
    "readOnly": {
      "isRequired": false,
      "type": "bool"
    },
    "selectOnFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium"
      ]
    }
  },
  "Avatar": {
    "alt": {
      "isRequired": false,
      "type": "string"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "sizes": {
      "isRequired": false,
      "type": "string"
    },
    "src": {
      "isRequired": false,
      "type": "string"
    },
    "srcSet": {
      "isRequired": false,
      "type": "string"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "circular",
        "rounded",
        "square"
      ]
    }
  },
  "AvatarGroup": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "spacing": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    },
    "total": {
      "isRequired": false,
      "type": "number"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "circular",
        "rounded",
        "square"
      ]
    }
  },
  "Backdrop": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "invisible": {
      "isRequired": false,
      "type": "bool"
    },
    "open": {
      "isRequired": true,
      "type": "bool"
    }
  },
  "Badge": {
    "badgeContent": {
      "isRequired": false,
      "type": "node"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "invisible": {
      "isRequired": false,
      "type": "bool"
    },
    "max": {
      "isRequired": false,
      "type": "number"
    },
    "overlap": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "circular",
        "rectangular"
      ]
    },
    "showZero": {
      "isRequired": false,
      "type": "bool"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dot",
        "standard"
      ]
    }
  },
  "BottomNavigation": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "showLabels": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "BottomNavigationAction": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "label": {
      "isRequired": false,
      "type": "node"
    },
    "showLabel": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Box": {
    "children": {
      "isRequired": false,
      "type": "node"
    }
  },
  "Breadcrumbs": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "expandText": {
      "isRequired": false,
      "type": "string"
    },
    "separator": {
      "isRequired": false,
      "type": "node"
    }
  },
  "Button": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "primary",
        "secondary",
        "success",
        "error",
        "info",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableElevation": {
      "isRequired": false,
      "type": "bool"
    },
    "disableFocusRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "endIcon": {
      "isRequired": false,
      "type": "node"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "href": {
      "isRequired": false,
      "type": "string"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    },
    "startIcon": {
      "isRequired": false,
      "type": "node"
    },
    "type": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "button",
        "reset",
        "submit"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "contained",
        "outlined",
        "text"
      ]
    }
  },
  "ButtonBase": {
    "centerRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "disableTouchRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "focusRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    },
    "tabIndex": {
      "isRequired": false,
      "type": "number"
    },
    "type": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "button",
        "reset",
        "submit"
      ]
    }
  },
  "ButtonGroup": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableElevation": {
      "isRequired": false,
      "type": "bool"
    },
    "disableFocusRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "orientation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "contained",
        "outlined",
        "text"
      ]
    }
  },
  "Card": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "CardActionArea": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    }
  },
  "CardActions": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableSpacing": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "CardContent": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "CardHeader": {
    "action": {
      "isRequired": false,
      "type": "node"
    },
    "avatar": {
      "isRequired": false,
      "type": "node"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableTypography": {
      "isRequired": false,
      "type": "bool"
    },
    "subheader": {
      "isRequired": false,
      "type": "node"
    },
    "title": {
      "isRequired": false,
      "type": "node"
    }
  },
  "CardMedia": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "image": {
      "isRequired": false,
      "type": "string"
    },
    "src": {
      "isRequired": false,
      "type": "string"
    }
  },
  "Checkbox": {
    "checked": {
      "isRequired": false,
      "type": "bool"
    },
    "checkedIcon": {
      "isRequired": false,
      "type": "node"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "defaultChecked": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "indeterminate": {
      "isRequired": false,
      "type": "bool"
    },
    "indeterminateIcon": {
      "isRequired": false,
      "type": "node"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    }
  },
  "Chip": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "clickable": {
      "isRequired": false,
      "type": "bool"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "label": {
      "isRequired": false,
      "type": "node"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined"
      ]
    }
  },
  "CircularProgress": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "thickness": {
      "isRequired": false,
      "type": "number"
    },
    "value": {
      "isRequired": false,
      "type": "number"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "determinate",
        "indeterminate"
      ]
    }
  },
  "Collapse": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "in": {
      "isRequired": false,
      "type": "bool"
    },
    "orientation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    },
    "timeout": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    }
  },
  "Container": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "disableGutters": {
      "isRequired": false,
      "type": "bool"
    },
    "fixed": {
      "isRequired": false,
      "type": "bool"
    },
    "maxWidth": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "xs",
        "sm",
        "md",
        "lg",
        "xl",
        false
      ]
    }
  },
  "CssBaseline": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "enableColorScheme": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Dialog": {
    "undefined": {
      "isRequired": false,
      "type": "string"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableEscapeKeyDown": {
      "isRequired": false,
      "type": "bool"
    },
    "fullScreen": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "maxWidth": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "xs",
        "sm",
        "md",
        "lg",
        "xl",
        false
      ]
    },
    "open": {
      "isRequired": true,
      "type": "bool"
    },
    "scroll": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "body",
        "paper"
      ]
    }
  },
  "DialogActions": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableSpacing": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "DialogContent": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "dividers": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "DialogContentText": {
    "children": {
      "isRequired": false,
      "type": "node"
    }
  },
  "DialogTitle": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    }
  },
  "Divider": {
    "absolute": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "flexItem": {
      "isRequired": false,
      "type": "bool"
    },
    "light": {
      "isRequired": false,
      "type": "bool"
    },
    "orientation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    },
    "role": {
      "isRequired": false,
      "type": "string"
    },
    "textAlign": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "center",
        "left",
        "right"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "fullWidth",
        "inset",
        "middle"
      ]
    }
  },
  "Drawer": {
    "anchor": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "bottom",
        "left",
        "right",
        "top"
      ]
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "hideBackdrop": {
      "isRequired": false,
      "type": "bool"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "permanent",
        "persistent",
        "temporary"
      ]
    }
  },
  "Fab": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "error",
        "info",
        "inherit",
        "primary",
        "secondary",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableFocusRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    },
    "href": {
      "isRequired": false,
      "type": "string"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "circular",
        "extended"
      ]
    }
  },
  "Fade": {
    "appear": {
      "isRequired": false,
      "type": "bool"
    },
    "in": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "FilledInput": {
    "autoComplete": {
      "isRequired": false,
      "type": "string"
    },
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableUnderline": {
      "isRequired": false,
      "type": "bool"
    },
    "endAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "hiddenLabel": {
      "isRequired": false,
      "type": "bool"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense",
        "none"
      ]
    },
    "multiline": {
      "isRequired": false,
      "type": "bool"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "placeholder": {
      "isRequired": false,
      "type": "string"
    },
    "readOnly": {
      "isRequired": false,
      "type": "bool"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "startAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "type": {
      "isRequired": false,
      "type": "string"
    }
  },
  "FormControl": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "focused": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "hiddenLabel": {
      "isRequired": false,
      "type": "bool"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense",
        "none",
        "normal"
      ]
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "FormControlLabel": {
    "checked": {
      "isRequired": false,
      "type": "bool"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableTypography": {
      "isRequired": false,
      "type": "bool"
    },
    "label": {
      "isRequired": false,
      "type": "node"
    },
    "labelPlacement": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "bottom",
        "end",
        "start",
        "top"
      ]
    },
    "name": {
      "isRequired": false,
      "type": "string"
    }
  },
  "FormGroup": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "row": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "FormHelperText": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "filled": {
      "isRequired": false,
      "type": "bool"
    },
    "focused": {
      "isRequired": false,
      "type": "bool"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense"
      ]
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "FormLabel": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "error",
        "info",
        "primary",
        "secondary",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "filled": {
      "isRequired": false,
      "type": "bool"
    },
    "focused": {
      "isRequired": false,
      "type": "bool"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "GlobalStyles": {},
  "Grid": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "container": {
      "isRequired": false,
      "type": "bool"
    },
    "direction": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "column-reverse",
        "column",
        "row-reverse",
        "row"
      ]
    },
    "item": {
      "isRequired": false,
      "type": "bool"
    },
    "lg": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "md": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "sm": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "wrap": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "nowrap",
        "wrap-reverse",
        "wrap"
      ]
    },
    "xl": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "xs": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "zeroMinWidth": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Grow": {
    "appear": {
      "isRequired": false,
      "type": "bool"
    },
    "in": {
      "isRequired": false,
      "type": "bool"
    },
    "timeout": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    }
  },
  "Hidden": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "implementation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "css",
        "js"
      ]
    },
    "initialWidth": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "xs",
        "sm",
        "md",
        "lg",
        "xl"
      ]
    },
    "lgDown": {
      "isRequired": false,
      "type": "bool"
    },
    "lgUp": {
      "isRequired": false,
      "type": "bool"
    },
    "mdDown": {
      "isRequired": false,
      "type": "bool"
    },
    "mdUp": {
      "isRequired": false,
      "type": "bool"
    },
    "only": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "xs",
        "sm",
        "md",
        "lg",
        "xl"
      ]
    },
    "smDown": {
      "isRequired": false,
      "type": "bool"
    },
    "smUp": {
      "isRequired": false,
      "type": "bool"
    },
    "xlDown": {
      "isRequired": false,
      "type": "bool"
    },
    "xlUp": {
      "isRequired": false,
      "type": "bool"
    },
    "xsDown": {
      "isRequired": false,
      "type": "bool"
    },
    "xsUp": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Icon": {
    "baseClassName": {
      "isRequired": false,
      "type": "string"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "action",
        "disabled",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "fontSize": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "large",
        "medium",
        "small"
      ]
    }
  },
  "IconButton": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "default",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableFocusRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "edge": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "end",
        "start",
        false
      ]
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    }
  },
  "ImageList": {
    "children": {
      "isRequired": true,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "gap": {
      "isRequired": false,
      "type": "number"
    },
    "rowHeight": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "masonry",
        "quilted",
        "standard",
        "woven"
      ]
    }
  },
  "ImageListItem": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "ImageListItemBar": {
    "actionIcon": {
      "isRequired": false,
      "type": "node"
    },
    "actionPosition": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "left",
        "right"
      ]
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "position": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "below",
        "bottom",
        "top"
      ]
    },
    "subtitle": {
      "isRequired": false,
      "type": "node"
    },
    "title": {
      "isRequired": false,
      "type": "node"
    }
  },
  "Input": {
    "autoComplete": {
      "isRequired": false,
      "type": "string"
    },
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableUnderline": {
      "isRequired": false,
      "type": "bool"
    },
    "endAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense",
        "none"
      ]
    },
    "multiline": {
      "isRequired": false,
      "type": "bool"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "placeholder": {
      "isRequired": false,
      "type": "string"
    },
    "readOnly": {
      "isRequired": false,
      "type": "bool"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "startAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "type": {
      "isRequired": false,
      "type": "string"
    }
  },
  "InputAdornment": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disablePointerEvents": {
      "isRequired": false,
      "type": "bool"
    },
    "disableTypography": {
      "isRequired": false,
      "type": "bool"
    },
    "position": {
      "isRequired": true,
      "type": "oneOf",
      "values": [
        "end",
        "start"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "InputBase": {
    "undefined": {
      "isRequired": false,
      "type": "string"
    },
    "autoComplete": {
      "isRequired": false,
      "type": "string"
    },
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableInjectingGlobalStyles": {
      "isRequired": false,
      "type": "bool"
    },
    "endAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense",
        "none"
      ]
    },
    "multiline": {
      "isRequired": false,
      "type": "bool"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "placeholder": {
      "isRequired": false,
      "type": "string"
    },
    "readOnly": {
      "isRequired": false,
      "type": "bool"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    },
    "startAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "type": {
      "isRequired": false,
      "type": "string"
    }
  },
  "InputLabel": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "error",
        "info",
        "primary",
        "secondary",
        "success",
        "warning"
      ]
    },
    "disableAnimation": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "focused": {
      "isRequired": false,
      "type": "bool"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense"
      ]
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "shrink": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "normal",
        "small"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "LinearProgress": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "primary",
        "secondary"
      ]
    },
    "value": {
      "isRequired": false,
      "type": "number"
    },
    "valueBuffer": {
      "isRequired": false,
      "type": "number"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "buffer",
        "determinate",
        "indeterminate",
        "query"
      ]
    }
  },
  "Link": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "underline": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "always",
        "hover",
        "none"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "body1",
        "body2",
        "button",
        "caption",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "inherit",
        "overline",
        "subtitle1",
        "subtitle2"
      ]
    }
  },
  "List": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "dense": {
      "isRequired": false,
      "type": "bool"
    },
    "disablePadding": {
      "isRequired": false,
      "type": "bool"
    },
    "subheader": {
      "isRequired": false,
      "type": "node"
    }
  },
  "ListItem": {
    "alignItems": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "center",
        "flex-start"
      ]
    },
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "button": {
      "isRequired": false,
      "type": "bool"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "dense": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableGutters": {
      "isRequired": false,
      "type": "bool"
    },
    "disablePadding": {
      "isRequired": false,
      "type": "bool"
    },
    "divider": {
      "isRequired": false,
      "type": "bool"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    },
    "secondaryAction": {
      "isRequired": false,
      "type": "node"
    },
    "selected": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "ListItemAvatar": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "ListItemButton": {
    "alignItems": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "center",
        "flex-start"
      ]
    },
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "dense": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableGutters": {
      "isRequired": false,
      "type": "bool"
    },
    "divider": {
      "isRequired": false,
      "type": "bool"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    },
    "href": {
      "isRequired": false,
      "type": "string"
    },
    "selected": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "ListItemIcon": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "ListItemSecondaryAction": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "ListItemText": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableTypography": {
      "isRequired": false,
      "type": "bool"
    },
    "inset": {
      "isRequired": false,
      "type": "bool"
    },
    "primary": {
      "isRequired": false,
      "type": "node"
    },
    "secondary": {
      "isRequired": false,
      "type": "node"
    }
  },
  "ListSubheader": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "inherit",
        "primary"
      ]
    },
    "disableGutters": {
      "isRequired": false,
      "type": "bool"
    },
    "disableSticky": {
      "isRequired": false,
      "type": "bool"
    },
    "inset": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Menu": {
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "disableAutoFocusItem": {
      "isRequired": false,
      "type": "bool"
    },
    "open": {
      "isRequired": true,
      "type": "bool"
    },
    "transitionDuration": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "menu",
        "selectedMenu"
      ]
    }
  },
  "MenuItem": {
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "dense": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableGutters": {
      "isRequired": false,
      "type": "bool"
    },
    "divider": {
      "isRequired": false,
      "type": "bool"
    },
    "focusVisibleClassName": {
      "isRequired": false,
      "type": "string"
    },
    "role": {
      "isRequired": false,
      "type": "string"
    },
    "selected": {
      "isRequired": false,
      "type": "bool"
    },
    "tabIndex": {
      "isRequired": false,
      "type": "number"
    },
    "value": {
      "isRequired": false,
      "type": "string"
    }
  },
  "MenuList": {
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "autoFocusItem": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disabledItemsFocusable": {
      "isRequired": false,
      "type": "bool"
    },
    "disableListWrap": {
      "isRequired": false,
      "type": "bool"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "menu",
        "selectedMenu"
      ]
    }
  },
  "MobileStepper": {
    "backButton": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "nextButton": {
      "isRequired": false,
      "type": "node"
    },
    "position": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "bottom",
        "static",
        "top"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dots",
        "progress",
        "text"
      ]
    }
  },
  "Modal": {
    "closeAfterTransition": {
      "isRequired": false,
      "type": "bool"
    },
    "disableAutoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "disableEnforceFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "disableEscapeKeyDown": {
      "isRequired": false,
      "type": "bool"
    },
    "disablePortal": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRestoreFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "disableScrollLock": {
      "isRequired": false,
      "type": "bool"
    },
    "hideBackdrop": {
      "isRequired": false,
      "type": "bool"
    },
    "keepMounted": {
      "isRequired": false,
      "type": "bool"
    },
    "open": {
      "isRequired": true,
      "type": "bool"
    }
  },
  "NativeSelect": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "OutlinedInput": {
    "autoComplete": {
      "isRequired": false,
      "type": "string"
    },
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "endAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "label": {
      "isRequired": false,
      "type": "node"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense",
        "none"
      ]
    },
    "multiline": {
      "isRequired": false,
      "type": "bool"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "notched": {
      "isRequired": false,
      "type": "bool"
    },
    "placeholder": {
      "isRequired": false,
      "type": "string"
    },
    "readOnly": {
      "isRequired": false,
      "type": "bool"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "startAdornment": {
      "isRequired": false,
      "type": "node"
    },
    "type": {
      "isRequired": false,
      "type": "string"
    }
  },
  "Pagination": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary",
        "standard"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "hideNextButton": {
      "isRequired": false,
      "type": "bool"
    },
    "hidePrevButton": {
      "isRequired": false,
      "type": "bool"
    },
    "shape": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "circular",
        "rounded"
      ]
    },
    "showFirstButton": {
      "isRequired": false,
      "type": "bool"
    },
    "showLastButton": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "outlined",
        "text"
      ]
    }
  },
  "PaginationItem": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary",
        "standard"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "page": {
      "isRequired": false,
      "type": "node"
    },
    "selected": {
      "isRequired": false,
      "type": "bool"
    },
    "shape": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "circular",
        "rounded"
      ]
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    },
    "type": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "end-ellipsis",
        "first",
        "last",
        "next",
        "page",
        "previous",
        "start-ellipsis"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "outlined",
        "text"
      ]
    }
  },
  "Paper": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "square": {
      "isRequired": false,
      "type": "bool"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "elevation",
        "outlined"
      ]
    }
  },
  "Popover": {
    "anchorReference": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "anchorEl",
        "anchorPosition",
        "none"
      ]
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "marginThreshold": {
      "isRequired": false,
      "type": "number"
    },
    "open": {
      "isRequired": true,
      "type": "bool"
    },
    "transitionDuration": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    }
  },
  "Popper": {
    "disablePortal": {
      "isRequired": false,
      "type": "bool"
    },
    "keepMounted": {
      "isRequired": false,
      "type": "bool"
    },
    "open": {
      "isRequired": true,
      "type": "bool"
    },
    "placement": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto-end",
        "auto-start",
        "auto",
        "bottom-end",
        "bottom-start",
        "bottom",
        "left-end",
        "left-start",
        "left",
        "right-end",
        "right-start",
        "right",
        "top-end",
        "top-start",
        "top"
      ]
    },
    "transition": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Radio": {
    "checked": {
      "isRequired": false,
      "type": "bool"
    },
    "checkedIcon": {
      "isRequired": false,
      "type": "node"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    }
  },
  "RadioGroup": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    }
  },
  "Rating": {
    "value": {
      "isRequired": false,
      "type": "number"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "emptyIcon": {
      "isRequired": false,
      "type": "node"
    },
    "focus": {
      "isRequired": true,
      "type": "number"
    },
    "highlightSelectedOnly": {
      "isRequired": false,
      "type": "bool"
    },
    "hover": {
      "isRequired": true,
      "type": "number"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "isActive": {
      "isRequired": true,
      "type": "bool"
    },
    "itemValue": {
      "isRequired": true,
      "type": "number"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "ratingValue": {
      "isRequired": false,
      "type": "number"
    },
    "ratingValueRounded": {
      "isRequired": false,
      "type": "number"
    },
    "readOnly": {
      "isRequired": false,
      "type": "bool"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "defaultValue": {
      "isRequired": false,
      "type": "number"
    },
    "emptyLabelText": {
      "isRequired": false,
      "type": "node"
    },
    "max": {
      "isRequired": false,
      "type": "number"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    }
  },
  "ScopedCssBaseline": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "enableColorScheme": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Select": {
    "autoWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "defaultOpen": {
      "isRequired": false,
      "type": "bool"
    },
    "displayEmpty": {
      "isRequired": false,
      "type": "bool"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "label": {
      "isRequired": false,
      "type": "node"
    },
    "labelId": {
      "isRequired": false,
      "type": "string"
    },
    "multiple": {
      "isRequired": false,
      "type": "bool"
    },
    "native": {
      "isRequired": false,
      "type": "bool"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "value": {
      "isRequired": false,
      "type": "string"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "Skeleton": {
    "animation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "pulse",
        "wave",
        false
      ]
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "circular",
        "rectangular",
        "rounded",
        "text"
      ]
    }
  },
  "Slide": {
    "appear": {
      "isRequired": false,
      "type": "bool"
    },
    "direction": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "down",
        "left",
        "right",
        "up"
      ]
    },
    "in": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Slider": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableSwap": {
      "isRequired": false,
      "type": "bool"
    },
    "isRtl": {
      "isRequired": false,
      "type": "bool"
    },
    "max": {
      "isRequired": false,
      "type": "number"
    },
    "min": {
      "isRequired": false,
      "type": "number"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "orientation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium"
      ]
    },
    "step": {
      "isRequired": false,
      "type": "number"
    },
    "tabIndex": {
      "isRequired": false,
      "type": "number"
    },
    "track": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inverted",
        "normal",
        false
      ]
    },
    "valueLabelDisplay": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto",
        "off",
        "on"
      ]
    }
  },
  "Snackbar": {
    "action": {
      "isRequired": false,
      "type": "node"
    },
    "autoHideDuration": {
      "isRequired": false,
      "type": "number"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableWindowBlurListener": {
      "isRequired": false,
      "type": "bool"
    },
    "message": {
      "isRequired": false,
      "type": "node"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "resumeHideDuration": {
      "isRequired": false,
      "type": "number"
    }
  },
  "SnackbarContent": {
    "action": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "message": {
      "isRequired": false,
      "type": "node"
    },
    "role": {
      "isRequired": false,
      "type": "string"
    }
  },
  "SpeedDial": {
    "ariaLabel": {
      "isRequired": true,
      "type": "string"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "direction": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "down",
        "left",
        "right",
        "up"
      ]
    },
    "hidden": {
      "isRequired": false,
      "type": "bool"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "openIcon": {
      "isRequired": false,
      "type": "node"
    }
  },
  "SpeedDialAction": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "delay": {
      "isRequired": false,
      "type": "number"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "tooltipOpen": {
      "isRequired": false,
      "type": "bool"
    },
    "tooltipPlacement": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "bottom-end",
        "bottom-start",
        "bottom",
        "left-end",
        "left-start",
        "left",
        "right-end",
        "right-start",
        "right",
        "top-end",
        "top-start",
        "top"
      ]
    },
    "tooltipTitle": {
      "isRequired": false,
      "type": "node"
    }
  },
  "SpeedDialIcon": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "openIcon": {
      "isRequired": false,
      "type": "node"
    }
  },
  "Stack": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "direction": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "column-reverse",
        "column",
        "row-reverse",
        "row"
      ]
    },
    "divider": {
      "isRequired": false,
      "type": "node"
    }
  },
  "Step": {
    "active": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "completed": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "expanded": {
      "isRequired": false,
      "type": "bool"
    },
    "last": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "StepButton": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "optional": {
      "isRequired": false,
      "type": "node"
    }
  },
  "StepConnector": {
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "StepContent": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "transitionDuration": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto"
      ]
    }
  },
  "StepIcon": {
    "active": {
      "isRequired": false,
      "type": "bool"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "completed": {
      "isRequired": false,
      "type": "bool"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    }
  },
  "StepLabel": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "optional": {
      "isRequired": false,
      "type": "node"
    }
  },
  "Stepper": {
    "alternativeLabel": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "nonLinear": {
      "isRequired": false,
      "type": "bool"
    },
    "orientation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    }
  },
  "SvgIcon": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "action",
        "disabled",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "fontSize": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "large",
        "medium",
        "small"
      ]
    },
    "htmlColor": {
      "isRequired": false,
      "type": "string"
    },
    "inheritViewBox": {
      "isRequired": false,
      "type": "bool"
    },
    "shapeRendering": {
      "isRequired": false,
      "type": "string"
    },
    "titleAccess": {
      "isRequired": false,
      "type": "string"
    },
    "viewBox": {
      "isRequired": false,
      "type": "string"
    }
  },
  "SwipeableDrawer": {
    "anchor": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "bottom",
        "left",
        "right",
        "top"
      ]
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "disableBackdropTransition": {
      "isRequired": false,
      "type": "bool"
    },
    "disableDiscovery": {
      "isRequired": false,
      "type": "bool"
    },
    "disableSwipeToOpen": {
      "isRequired": false,
      "type": "bool"
    },
    "hideBackdrop": {
      "isRequired": false,
      "type": "bool"
    },
    "hysteresis": {
      "isRequired": false,
      "type": "number"
    },
    "minFlingVelocity": {
      "isRequired": false,
      "type": "number"
    },
    "open": {
      "isRequired": true,
      "type": "bool"
    },
    "swipeAreaWidth": {
      "isRequired": false,
      "type": "number"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "permanent",
        "persistent",
        "temporary"
      ]
    }
  },
  "Switch": {
    "checked": {
      "isRequired": false,
      "type": "bool"
    },
    "checkedIcon": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "default",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "defaultChecked": {
      "isRequired": false,
      "type": "bool"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "edge": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "end",
        "start",
        false
      ]
    },
    "icon": {
      "isRequired": false,
      "type": "node"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    }
  },
  "Tab": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableFocusRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "iconPosition": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "bottom",
        "end",
        "start",
        "top"
      ]
    },
    "label": {
      "isRequired": false,
      "type": "node"
    },
    "wrapped": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "TabScrollButton": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "direction": {
      "isRequired": true,
      "type": "oneOf",
      "values": [
        "left",
        "right"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "orientation": {
      "isRequired": true,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    }
  },
  "Table": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "padding": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "checkbox",
        "none",
        "normal"
      ]
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    },
    "stickyHeader": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "TableBody": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "TableCell": {
    "align": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "center",
        "inherit",
        "justify",
        "left",
        "right"
      ]
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "padding": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "checkbox",
        "none",
        "normal"
      ]
    },
    "scope": {
      "isRequired": false,
      "type": "string"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    },
    "sortDirection": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "asc",
        "desc",
        false
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "body",
        "footer",
        "head"
      ]
    }
  },
  "TableContainer": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "TableFooter": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "TableHead": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    }
  },
  "TablePagination": {
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "colSpan": {
      "isRequired": false,
      "type": "number"
    },
    "labelRowsPerPage": {
      "isRequired": false,
      "type": "node"
    },
    "showFirstButton": {
      "isRequired": false,
      "type": "bool"
    },
    "showLastButton": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "TableRow": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "hover": {
      "isRequired": false,
      "type": "bool"
    },
    "selected": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "TableSortLabel": {
    "active": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "direction": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "asc",
        "desc"
      ]
    },
    "hideSortIcon": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "Tabs": {
    "allowScrollButtonsMobile": {
      "isRequired": false,
      "type": "bool"
    },
    "undefined": {
      "isRequired": false,
      "type": "string"
    },
    "centered": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "indicatorColor": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary"
      ]
    },
    "orientation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    },
    "scrollButtons": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "auto",
        false,
        true
      ]
    },
    "selectionFollowsFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "textColor": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "inherit",
        "primary",
        "secondary"
      ]
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "fullWidth",
        "scrollable",
        "standard"
      ]
    },
    "visibleScrollbar": {
      "isRequired": false,
      "type": "bool"
    }
  },
  "TextField": {
    "autoComplete": {
      "isRequired": false,
      "type": "string"
    },
    "autoFocus": {
      "isRequired": false,
      "type": "bool"
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "error": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "helperText": {
      "isRequired": false,
      "type": "node"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "label": {
      "isRequired": false,
      "type": "node"
    },
    "margin": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense",
        "none",
        "normal"
      ]
    },
    "multiline": {
      "isRequired": false,
      "type": "bool"
    },
    "name": {
      "isRequired": false,
      "type": "string"
    },
    "placeholder": {
      "isRequired": false,
      "type": "string"
    },
    "required": {
      "isRequired": false,
      "type": "bool"
    },
    "select": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "medium",
        "small"
      ]
    },
    "type": {
      "isRequired": false,
      "type": "string"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "filled",
        "outlined",
        "standard"
      ]
    }
  },
  "ToggleButton": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "standard",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "disableFocusRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "disableRipple": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "selected": {
      "isRequired": false,
      "type": "bool"
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    }
  },
  "ToggleButtonGroup": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "color": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "standard",
        "primary",
        "secondary",
        "error",
        "info",
        "success",
        "warning"
      ]
    },
    "disabled": {
      "isRequired": false,
      "type": "bool"
    },
    "exclusive": {
      "isRequired": false,
      "type": "bool"
    },
    "fullWidth": {
      "isRequired": false,
      "type": "bool"
    },
    "orientation": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "horizontal",
        "vertical"
      ]
    },
    "size": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "small",
        "medium",
        "large"
      ]
    }
  },
  "Toolbar": {
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "disableGutters": {
      "isRequired": false,
      "type": "bool"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "dense",
        "regular"
      ]
    }
  },
  "Tooltip": {
    "arrow": {
      "isRequired": false,
      "type": "bool"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "describeChild": {
      "isRequired": false,
      "type": "bool"
    },
    "disableFocusListener": {
      "isRequired": false,
      "type": "bool"
    },
    "disableHoverListener": {
      "isRequired": false,
      "type": "bool"
    },
    "disableInteractive": {
      "isRequired": false,
      "type": "bool"
    },
    "disableTouchListener": {
      "isRequired": false,
      "type": "bool"
    },
    "enterDelay": {
      "isRequired": false,
      "type": "number"
    },
    "enterNextDelay": {
      "isRequired": false,
      "type": "number"
    },
    "enterTouchDelay": {
      "isRequired": false,
      "type": "number"
    },
    "followCursor": {
      "isRequired": false,
      "type": "bool"
    },
    "id": {
      "isRequired": false,
      "type": "string"
    },
    "leaveDelay": {
      "isRequired": false,
      "type": "number"
    },
    "leaveTouchDelay": {
      "isRequired": false,
      "type": "number"
    },
    "open": {
      "isRequired": false,
      "type": "bool"
    },
    "placement": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "bottom-end",
        "bottom-start",
        "bottom",
        "left-end",
        "left-start",
        "left",
        "right-end",
        "right-start",
        "right",
        "top-end",
        "top-start",
        "top"
      ]
    },
    "title": {
      "isRequired": true,
      "type": "node"
    }
  },
  "Typography": {
    "align": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "center",
        "inherit",
        "justify",
        "left",
        "right"
      ]
    },
    "children": {
      "isRequired": false,
      "type": "node"
    },
    "className": {
      "isRequired": false,
      "type": "string"
    },
    "gutterBottom": {
      "isRequired": false,
      "type": "bool"
    },
    "noWrap": {
      "isRequired": false,
      "type": "bool"
    },
    "paragraph": {
      "isRequired": false,
      "type": "bool"
    },
    "variant": {
      "isRequired": false,
      "type": "oneOf",
      "values": [
        "body1",
        "body2",
        "button",
        "caption",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "inherit",
        "overline",
        "subtitle1",
        "subtitle2"
      ]
    }
  },
  "Zoom": {
    "appear": {
      "isRequired": false,
      "type": "bool"
    },
    "in": {
      "isRequired": false,
      "type": "bool"
    }
  }
} as const;
export default propTypes;
